# Generated by Django 5.1.6 on 2025-02-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='challenge',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
